name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*"]

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (local, pour scanner)
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile.multi
          load: true
          tags: demo-api:ci

      - name: Scan Trivy (gate)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: demo-api:ci
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1" # la CI échoue si une CVE HIGH/CRITICAL corrigeable est trouvée
          format: table
